### ISSUE TITLE
Traefic service deployed twice on manager nodes on 6 node cluster (3+3)

### ISSUE THREAD

**Issue by baskinsy** [tiangolo/dockerswarm.rocks#2]
Hello, I greatly appreciate your guides and the technical details. I have found them very helpful on my research on swarm.

I have a simple question. As the title describes when using 

`export TRAEFIK_REPLICAS=$(docker node ls -q | wc -l)`

on a 6 node swarm cluster with 3 managers and 3 workers because of this constraint

```
deploy:
      replicas: ${TRAEFIK_REPLICAS:-3}
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
```

results on 2 traefic containers per manager node (total 6 as the number of replicas). This is an expected behavior as I can understood but I cannot answer if the correct is to have one replica per node so the "manager" constraint has to be removed, or 3 replicas running only on manager nodes are enough.

With the current deployment of 6 replicas (2 per manager node) everything seems to work and by adding all my 6 nodes to a round robin dns I get correct behavior but I don't know if this is ideal due to the question regarding the placement and the number of the traefic replicas.

Maybe I'm missing something but if you can clarify more I will be grateful. Thanks in advance.
