### ISSUE TITLE
Not getting ssl

### ISSUE THREAD

**Issue by raphawa** [tiangolo/dockerswarm.rocks#38]
I'm trying to setup wordpress stack behind the traefik in docker swarm but not allways get ssl error and can't access website.

here is my compose file

```YAML
version: '3'

networks:
  traefik-public:
    external: true
  internalwp:
    external: false

services:
 wordpress:
  image: wordpress:5.4.1-php7.2-apache
  depends_on:
  - mariadb
  volumes:
  - orgwerimawp:/var/www/html/wp-content
  environment:
   WORDPRESS_DB_HOST: xxxxxxxxxxxxxxxxxxxxxxxxxx
   WORDPRESS_DB_PASSWORD: xxxxxxxxxxxxxxxxxx
   WORDPRESS_DB_USER: xxxxxxxxxxxxxxxxxxxxx
   WORDPRESS_DB_NAME: xxxxxxxxxxxxxxxxxxxxxxxxx
   WORDPRESS_CONFIG_EXTRA: |
        /* Multisite */
        define('WP_ALLOW_MULTISITE', true );
        define('MULTISITE', true);
        define('SUBDOMAIN_INSTALL', true);
        define('DOMAIN_CURRENT_SITE', 'exempl.com'); // TODO: change to actual domain when deploying
        define('PATH_CURRENT_SITE', '/');
        define('SITE_ID_CURRENT_SITE', 1);
        define('BLOG_ID_CURRENT_SITE', 1);
 
  deploy:
      placement:
        constraints:
          - node.role == worker
  labels:
        - traefik.frontend.rule=Host: exempl.com
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https
  networks:
    - traefik-public
    - internalwp


 mariadb:
  image: mariadb:10.5.3
  volumes:
  - orgdb:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: xxxxxxxxxxxxxxxxxx
   MYSQL_DATABASE: xxxxxxxxxxxxxxxxx
   MYSQL_USER: xxxxxxxxxxxxxxx
   MYSQL_PASSWORD: xxxxxxxxxxxxxxxxxx  
  restart: always
  deploy:
      placement:
        constraints:
          - node.role == worker    
  networks:
    - internalwp
  labels:
      - traefik.enable=false

volumes:
   orgwp: 
   orgdb:
```
