### ISSUE TITLE
Using Docker swarm secrets for the Traefik dashboard

### ISSUE THREAD

**Issue by Midnighter** [tiangolo/dockerswarm.rocks#47]
In the section https://dockerswarm.rocks/traefik/#preparation, the current guide suggests to store the Basic auth information in environment variables. I found it much easier to handle (and probably safer, too), to use a Docker secret.

You can generate such a file using the Apache utility `htpasswd`:

```
mkdir secrets
htpasswd -Bc -C 16 secrets/basic_auth_users.txt admin
```

Then specify the secret in the `docker-compose.yml` and let your traefik service use it:

```yml
secrets:
  basic_auth_users:
    file: ./secrets/basic_auth_users.txt

services:
  traefik:
    ...
    secrets:
    - basic_auth_users
    ...
      labels:
      ...
      - "traefik.http.routers.traefik.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.usersfile=/run/secrets/basic_auth_users"
```

That way you can actually add multiple users to the file, too.

I'm happy to make a PR to the docs if desired.
