### ISSUE TITLE
Question on GitLab deployment

### ISSUE THREAD

**Issue by jamesthesken** [tiangolo/dockerswarm.rocks#61]
Hi @tiangolo thank you for this guide, I've gotten a lot better at Docker configurations since reading it!

On the page, [GitLab CI runner for CI/CD](https://dockerswarm.rocks/gitlab-ci/), I can't get the deploy stage to work for my stack. The build stage works fine, however I receive the error:
```
this node is not a swarm manager. Use "docker swarm init" or "docker swarm join"
to connect this node to swarm and try again
```

My `.gitlab-ci.yml`:

```
image: docker:19.03.12

services:
    - docker:19.03.12-dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - export IMAGE_NAME=$CI_REGISTRY_IMAGE:latest

variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - deploy

build-prod:
  stage: build
  script:
    - cd ./frontend
    - docker build -t $IMAGE_NAME -f Dockerfile.prod .
    - docker push $IMAGE_NAME
  only:
    - nextjs

deploy-prod:
  stage: deploy
  script:
    - docker stack deploy -c nextjs.yml --with-registry-auth nextjs
  only:
    - nextjs
```

Would it help by using your image, `tiangolo/docker-with-compose`? Thank you for your help.
