### ISSUE TITLE
Adding thelounge to swarm results in 404 error

### ISSUE THREAD

**Issue by noobcoder1983** [tiangolo/dockerswarm.rocks#8]
Hello, Sebastián,

we e-mailed a few days ago. Unfortunately I didn't get any further to start thelounge (https://hub.docker.com/r/thelounge/thelounge/), but like colleagues here I get the 404 error from traefik.

My thelounge.yml file looks like this:

```
version: '3.3'

services:
  thelounge:
    image: thelounge/thelounge:latest
    volumes:
      - thelounge:/data
      #- ~/data/thelounge:/var/opt/thelounge
    ports:
        - "4000:4000"
    labels:
      # - traefik.backend=thelounge
      - traefik.enable=true
      - traefik.frontend.rule=Host:${DOMAIN}
      - traefik.port=4000
      - traefik.docker.network=traefik-public
      - traefik.tags=traefik-public
      # Traefik service that listens to HTTP
      - traefik.redirectorservice.frontend.entryPoints=http
      - traefik.redirectorservice.frontend.redirect.entryPoint=https
      # Traefik service that listens to HTTPS
      - traefik.webservice.frontend.entryPoints=https      
    networks:
      #- web
      - traefik-public

networks:
  traefik-public:
    external: true

volumes:
  thelounge:
```

What did I do wrong? Can anyone please help me with my problem?

Edit: I also tried:

```
version: '3.3'

services:
  thelounge:
    image: thelounge/thelounge:latest
    volumes:
      - thelounge:/data
    labels:
      # - traefik.backend=thelounge
      - traefik.enable=true
      - traefik.frontend.rule=Host:${DOMAIN}
      - traefik.port=4000
      - traefik.docker.network=traefik-public
      - traefik.tags=traefik-public
      # Traefik service that listens to HTTP
      - traefik.redirectorservice.frontend.entryPoints=http
      - traefik.redirectorservice.frontend.redirect.entryPoint=https
      # Traefik service that listens to HTTPS
      - traefik.webservice.frontend.entryPoints=https      
    networks:
      #- web
      - traefik-public

networks:
  traefik-public:
    external: true

volumes:
  thelounge:

```

Also the 404 error appears. :-(

**Comment by noobcoder1983** [comment]
I also tried this but also this results in a 404 error:

`version: '3.3'

services:
  thelounge:
    image: thelounge/thelounge:latest
    volumes:
      - thelounge-data:/data
      #- ~/data/thelounge:/var/opt/thelounge
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.labels.thelounge.thelounge-data == true
    labels:
      # - traefik.backend=thelounge
      - traefik.enable=true
      - traefik.frontend.rule=Host:${DOMAIN}
      - traefik.port=4000
      - traefik.docker.network=traefik-public
      - traefik.tags=traefik-public
      # Traefik service that listens to HTTP
      - traefik.redirectorservice.frontend.entryPoints=http
      - traefik.redirectorservice.frontend.redirect.entryPoint=https
      # Traefik service that listens to HTTPS
      - traefik.webservice.frontend.entryPoints=https      
    networks:
      #- web
      - traefik-public

networks:
  traefik-public:
    external: true

volumes:
  thelounge-data:

`

any ideas what I have done wrong?

Thanks!

**Comment by noobcoder1983** [comment]
@tiangolo ok thanks I get the following log output:

```
3wnmgec 2019-05-10 17:10:37 [INFO] Configuration file created at /var/opt/thelounge/config.js.
3wnmgec 2019-05-10 17:10:38 [INFO] The Lounge v3.0.1 (Node.js 10.15.1 on linux x64)
3wnmgec 2019-05-10 17:10:38 [INFO] Configuration file: /var/opt/thelounge/config.js
3wnmgec 2019-05-10 17:10:38 [INFO] Available at http://:::9000/ in private mode
3wnmgec 2019-05-10 17:10:38 [INFO] New VAPID key pair has been generated for use with push subscription.
3wnmgec 2019-05-10 17:10:38 [INFO] There are currently no users. Create one with thelounge add <name>.
```

In my config I defined port number 4000. And on the host /var/opt/theloung/config.js is not present. What I have done wrong? Where I should edit and update the port because the default port of thelounge is 9000?

**Comment by rayrrr** [comment]
Try indenting your whole `labels` block so that it is under the `deploy` directive (even with `placement` in your last example). That got it working for me!

**Comment by noobcoder1983** [comment]
Thanks you mean like:
```

version: '3.3'

services:
  thelounge:
    image: thelounge/thelounge:latest
    volumes:
      - thelounge-data:/data
      #- ~/data/thelounge:/var/opt/thelounge
    networks:
      - traefik-public
    labels:
      # - traefik.backend=thelounge
      - traefik.enable=true
      - traefik.frontend.rule=Host:${DOMAIN}
      - traefik.port=4000
      - traefik.docker.network=traefik-public
      - traefik.tags=traefik-public
      # Traefik service that listens to HTTP
      - traefik.redirectorservice.frontend.entryPoints=http
      - traefik.redirectorservice.frontend.redirect.entryPoint=https
      # Traefik service that listens to HTTPS
      - traefik.webservice.frontend.entryPoints=https      
    networks:
      #- web
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.labels.thelounge.thelounge-data == true

networks:
  traefik-public:
    external: true

volumes:
  thelounge-data:
```

**Comment by rayrrr** [comment]
No that is not what I meant.

**Comment by tiangolo** [comment]
@noobcoder1983 what @rayrrr is saying is that you should put the labels inside the `deploy` key, something like:

```YAML
version: '3.3'

services:
  thelounge:
    image: thelounge/thelounge:latest
    volumes:
      - thelounge-data:/data
      #- ~/data/thelounge:/var/opt/thelounge
    networks:
      - traefik-public
    networks:
      #- web
      - traefik-public
    deploy:
      labels:
        # - traefik.backend=thelounge
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN}
        - traefik.port=4000
        - traefik.docker.network=traefik-public
        - traefik.tags=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https      
      placement:
        constraints:
          - node.role == manager
          - node.labels.thelounge.thelounge-data == true

networks:
  traefik-public:
    external: true

volumes:
  thelounge-data:
```

---

Also, as your app seems to be running on port `9000` you probably should declare it as such:

```YAML
version: '3.3'

services:
  thelounge:
    image: thelounge/thelounge:latest
    volumes:
      - thelounge-data:/data
      #- ~/data/thelounge:/var/opt/thelounge
    networks:
      - traefik-public
    networks:
      #- web
      - traefik-public
    deploy:
      labels:
        # - traefik.backend=thelounge
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN}
        - traefik.port=9000
        - traefik.docker.network=traefik-public
        - traefik.tags=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https      
      placement:
        constraints:
          - node.role == manager
          - node.labels.thelounge.thelounge-data == true

networks:
  traefik-public:
    external: true

volumes:
  thelounge-data:
```

**Comment by noobcoder1983** [comment]
Ok thank you very much for your hints. I will try that :-) When the lounge uses that port and another container is using that port too. What could be the best way to edit thelounge port in the config.js?

**Comment by tiangolo** [comment]
See my response here: https://github.com/tiangolo/dockerswarm.rocks/issues/4#issuecomment-491513714

**Comment by noobcoder1983** [comment]
Thanks!

**Comment by noobcoder1983** [comment]
Nope that does not help. I tried this:

```
export NODE_ID=$(docker info -f '{{.Swarm.NodeID}}')
docker node update --label-add thelounge.thelounge-data=true $NODE_ID
```

with the new .yml file you posted above. Error 404 appears again. :-(

**Comment by tiangolo** [comment]
@noobcoder1983 I think I have a gift for you :gift: 

https://dockerswarm.rocks/thelounge/

**Comment by noobcoder1983** [comment]
@tiangolo Thank you so much for your efforts and for the gift. So I was probably close when I compare the compose files. Well, just next to it is also over.

Oh, and it works fine. Hm if I can make it to get run Gitea (https://hub.docker.com/r/gitea/gitea)?

**Comment by tiangolo** [comment]
Yep, the process would be similar for Gitea.

**Comment by noobcoder1983** [comment]
Hmm I tried that:

```
version: '3.3'

services:
  app:
    image: gitea/gitea:latest
    volumes:
      - gitea-data:/data
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.gitea.gitea-data == true
      labels:
	- traefik.frontend.rule=Host:${DOMAIN}
        - traefik.enable=true
        - traefik.port=9000
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
      #enviroment:
        - USER_UID=1000
        - USER_GID=1000
      #ports:
	- "2221:22"
networks:
  traefik-public:
    external: true

volumes:
  gitea-data:

```

But I am always getting the error:

`Bad gateway` from traefik
